server:
  port: 9090
  
#Below lines were added by Ramesh K to print all queries  
#To enable Logging  - below are the sql log properties
logging:
  level:
    root: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace


## H2 Servlet setting
spring:
  ## Thymeleaf configuration:
  thymeleaf:
     cache: false
     mode: LEGACYHTML5
  resources:
     cache-period: 0
  
  # H2 database configuration 
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /admin/h2

  datasource:
    url: jdbc:h2:mem:dataSource;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect  
    
  ldap:
       embedded:
            ldif: classpath:/ldif/calendar.ldif
            base-dn: dc=jbcpcalendar,dc=com
            port: 33389
    